import i18n from '../../common/lang/index'
const commandDescriptions = Object.freeze({
  // ============================================
  // # Key binding descriptions
  // #

  'mt.hide': i18n.t('file.preferences.keybindings.keysDesc.mt.hide'),
  'mt.hide-others': i18n.t('file.preferences.keybindings.keysDesc.mt.hideOthers'),
  'file.new-window': i18n.t('file.preferences.keybindings.keysDesc.file.newWindow'),
  'file.new-tab': i18n.t('file.preferences.keybindings.keysDesc.file.newTab'),
  'file.open-file': i18n.t('file.preferences.keybindings.keysDesc.file.openFile'),
  'file.open-folder': i18n.t('file.preferences.keybindings.keysDesc.file.openFolder'),
  'file.save': i18n.t('file.preferences.keybindings.keysDesc.file.save'),
  'file.save-as': i18n.t('file.preferences.keybindings.keysDesc.file.saveAs'),
  'file.move-file': i18n.t('file.preferences.keybindings.keysDesc.file.moveFile'),
  'file.rename-file': i18n.t('file.preferences.keybindings.keysDesc.file.renameFile'),
  'file.quick-open': i18n.t('file.preferences.keybindings.keysDesc.file.quickOpen'),
  'file.print': i18n.t('file.preferences.keybindings.keysDesc.file.print'),
  'file.preferences': i18n.t('file.preferences.keybindings.keysDesc.file.preferences'),
  'file.close-tab': i18n.t('file.preferences.keybindings.keysDesc.file.closeTab'),
  'file.close-window': i18n.t('file.preferences.keybindings.keysDesc.file.closeWindow'),
  'file.quit': i18n.t('file.preferences.keybindings.keysDesc.file.quit'),
  'edit.undo': i18n.t('file.preferences.keybindings.keysDesc.edit.undo'),
  'edit.redo': i18n.t('file.preferences.keybindings.keysDesc.edit.redo'),
  'edit.cut': i18n.t('file.preferences.keybindings.keysDesc.edit.cut'),
  'edit.copy': i18n.t('file.preferences.keybindings.keysDesc.edit.copy'),
  'edit.paste': i18n.t('file.preferences.keybindings.keysDesc.edit.paste'),
  'edit.copy-as-markdown': i18n.t('file.preferences.keybindings.keysDesc.edit.copyAsMarkdown'),
  'edit.copy-as-html': i18n.t('file.preferences.keybindings.keysDesc.edit.copyAsHtml'),
  'edit.paste-as-plaintext': i18n.t('file.preferences.keybindings.keysDesc.edit.pasteAsPlaintext'),
  'edit.select-all': i18n.t('file.preferences.keybindings.keysDesc.edit.selectAll'),
  'edit.duplicate': i18n.t('file.preferences.keybindings.keysDesc.edit.duplicate'),
  'edit.create-paragraph': i18n.t('file.preferences.keybindings.keysDesc.edit.createParagraph'),
  'edit.delete-paragraph': i18n.t('file.preferences.keybindings.keysDesc.edit.deleteParagraph'),
  'edit.find': i18n.t('file.preferences.keybindings.keysDesc.edit.find'),
  'edit.find-next': i18n.t('file.preferences.keybindings.keysDesc.edit.findNext'),
  'edit.find-previous': i18n.t('file.preferences.keybindings.keysDesc.edit.findPrevious'),
  'edit.replace': i18n.t('file.preferences.keybindings.keysDesc.edit.replace'),
  'edit.find-in-folder': i18n.t('file.preferences.keybindings.keysDesc.edit.findInFolder'),
  'edit.screenshot': i18n.t('file.preferences.keybindings.keysDesc.edit.screenshot'),
  'paragraph.heading-1': i18n.t('file.preferences.keybindings.keysDesc.paragraph.heading1'),
  'paragraph.heading-2': i18n.t('file.preferences.keybindings.keysDesc.paragraph.heading2'),
  'paragraph.heading-3': i18n.t('file.preferences.keybindings.keysDesc.paragraph.heading3'),
  'paragraph.heading-4': i18n.t('file.preferences.keybindings.keysDesc.paragraph.heading4'),
  'paragraph.heading-5': i18n.t('file.preferences.keybindings.keysDesc.paragraph.heading5'),
  'paragraph.heading-6': i18n.t('file.preferences.keybindings.keysDesc.paragraph.heading6'),
  'paragraph.upgrade-heading': i18n.t('file.preferences.keybindings.keysDesc.paragraph.upgradeHeading'),
  'paragraph.degrade-heading': i18n.t('file.preferences.keybindings.keysDesc.paragraph.degradeHeading'),
  'paragraph.table': i18n.t('file.preferences.keybindings.keysDesc.paragraph.table'),
  'paragraph.code-fence': i18n.t('file.preferences.keybindings.keysDesc.paragraph.codeFence'),
  'paragraph.quote-block': i18n.t('file.preferences.keybindings.keysDesc.paragraph.quoteBlock'),
  'paragraph.math-formula': i18n.t('file.preferences.keybindings.keysDesc.paragraph.mathFormula'),
  'paragraph.html-block': i18n.t('file.preferences.keybindings.keysDesc.paragraph.htmlBlock'),
  'paragraph.order-list': i18n.t('file.preferences.keybindings.keysDesc.paragraph.orderList'),
  'paragraph.bullet-list': i18n.t('file.preferences.keybindings.keysDesc.paragraph.bulletList'),
  'paragraph.task-list': i18n.t('file.preferences.keybindings.keysDesc.paragraph.taskList'),
  'paragraph.loose-list-item': i18n.t('file.preferences.keybindings.keysDesc.paragraph.looseListItem'),
  'paragraph.paragraph': i18n.t('file.preferences.keybindings.keysDesc.paragraph.paragraph'),
  'paragraph.horizontal-line': i18n.t('file.preferences.keybindings.keysDesc.paragraph.horizontalLine'),
  'paragraph.front-matter': i18n.t('file.preferences.keybindings.keysDesc.paragraph.frontMatter'),
  'format.strong': i18n.t('file.preferences.keybindings.keysDesc.format.strong'),
  'format.emphasis': i18n.t('file.preferences.keybindings.keysDesc.format.emphasis'),
  'format.underline': i18n.t('file.preferences.keybindings.keysDesc.format.underline'),
  'format.superscript': i18n.t('file.preferences.keybindings.keysDesc.format.superscript'),
  'format.subscript': i18n.t('file.preferences.keybindings.keysDesc.format.subscript'),
  'format.highlight': i18n.t('file.preferences.keybindings.keysDesc.format.highlight'),
  'format.inline-code': i18n.t('file.preferences.keybindings.keysDesc.format.inlineCode'),
  'format.inline-math': i18n.t('file.preferences.keybindings.keysDesc.format.inlineMath'),
  'format.strike': i18n.t('file.preferences.keybindings.keysDesc.format.strike'),
  'format.hyperlink': i18n.t('file.preferences.keybindings.keysDesc.format.hyperlink'),
  'format.image': i18n.t('file.preferences.keybindings.keysDesc.format.image'),
  'format.clear-format': i18n.t('file.preferences.keybindings.keysDesc.format.clearFormat'),
  'window.minimize': i18n.t('file.preferences.keybindings.keysDesc.window.minimize'),
  'window.toggle-always-on-top': i18n.t('file.preferences.keybindings.keysDesc.window.toggleAlwaysOnTop'),
  'window.zoom-in': i18n.t('file.preferences.keybindings.keysDesc.window.zoomIn'),
  'window.zoom-out': i18n.t('file.preferences.keybindings.keysDesc.window.zoomOut'),
  'window.toggle-full-screen': i18n.t('file.preferences.keybindings.keysDesc.window.toggleFullScreen'),
  'view.command-palette': i18n.t('file.preferences.keybindings.keysDesc.view.commandPalette'),
  'view.source-code-mode': i18n.t('file.preferences.keybindings.keysDesc.view.sourceCodeMode'),
  'view.typewriter-mode': i18n.t('file.preferences.keybindings.keysDesc.view.typewriterCode'),
  'view.focus-mode': i18n.t('file.preferences.keybindings.keysDesc.view.focusMode'),
  'view.toggle-sidebar': i18n.t('file.preferences.keybindings.keysDesc.view.toggleSidebar'),
  'view.toggle-toc': i18n.t('file.preferences.keybindings.keysDesc.view.toggleToc'),
  'view.toggle-tabbar': i18n.t('file.preferences.keybindings.keysDesc.view.toggleTabbar'),
  'view.toggle-dev-tools': i18n.t('file.preferences.keybindings.keysDesc.view.toggleDevTools'),
  'view.dev-reload': i18n.t('file.preferences.keybindings.keysDesc.view.devReload'),
  'tabs.cycle-forward': i18n.t('file.preferences.keybindings.keysDesc.tabs.cycleForward'),
  'tabs.cycle-backward': i18n.t('file.preferences.keybindings.keysDesc.tabs.cycleBackward'),
  'tabs.switch-to-left': i18n.t('file.preferences.keybindings.keysDesc.tabs.switch2left'),
  'tabs.switch-to-right': i18n.t('file.preferences.keybindings.keysDesc.tabs.switch2right'),
  'tabs.switch-to-first': i18n.t('file.preferences.keybindings.keysDesc.tabs.switch2first'),
  'tabs.switch-to-second': i18n.t('file.preferences.keybindings.keysDesc.tabs.switch2second'),
  'tabs.switch-to-third': i18n.t('file.preferences.keybindings.keysDesc.tabs.switch2third'),
  'tabs.switch-to-fourth': i18n.t('file.preferences.keybindings.keysDesc.tabs.switch2fourth'),
  'tabs.switch-to-fifth': i18n.t('file.preferences.keybindings.keysDesc.tabs.switch2fifth'),
  'tabs.switch-to-sixth': i18n.t('file.preferences.keybindings.keysDesc.tabs.switch2sixth'),
  'tabs.switch-to-seventh': i18n.t('file.preferences.keybindings.keysDesc.tabs.switch2seventh'),
  'tabs.switch-to-eighth': i18n.t('file.preferences.keybindings.keysDesc.tabs.switch2eighth'),
  'tabs.switch-to-ninth': i18n.t('file.preferences.keybindings.keysDesc.tabs.switch2ninth'),
  'tabs.switch-to-tenth': i18n.t('file.preferences.keybindings.keysDesc.tabs.switch2tenth'),

  // ============================================
  // # Menu descriptions but not available as command
  // #

  'view.reload-images': i18n.t('file.preferences.keybindings.keysDesc.view.reloadImages'),

  // ============================================
  // # Additional command descriptions
  // #

  'file.toggle-auto-save': i18n.t('file.preferences.keybindings.keysDesc.file.toggleAutoSave'),
  'file.import-file': i18n.t('file.preferences.keybindings.keysDesc.file.importFile'),
  'file.export-file': i18n.t('file.preferences.keybindings.keysDesc.file.exportFile'),
  'file.zoom': i18n.t('file.preferences.keybindings.keysDesc.file.zoom'),
  'file.check-update': i18n.t('file.preferences.keybindings.keysDesc.file.checkUpdate'),
  'paragraph.reset-paragraph': i18n.t('file.preferences.keybindings.keysDesc.paragraph.resetParagraph'),
  'window.change-theme': i18n.t('file.preferences.keybindings.keysDesc.window.changeTheme'),
  'view.text-direction': i18n.t('file.preferences.keybindings.keysDesc.view.textDirection'),
  'docs.user-guide': i18n.t('file.preferences.keybindings.keysDesc.docs.userGuide'),
  'docs.markdown-syntax': i18n.t('file.preferences.keybindings.keysDesc.docs.markdownSyntax')
})

export default id => {
  return commandDescriptions[id]
}
